apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webserver1
  namespace: webserver1
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: webserver1
      spec:
        source:
          http:
            url: 'https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-x86_64-9-latest.x86_64.qcow2'
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          volumeMode: Filesystem
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: webserver1
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: webserver1
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              macAddress: '02:17:19:00:00:11'
              model: virtio
              name: nic-localnet
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
        - multus:
            networkName: localnet-network
          name: nic-localnet
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: webserver1
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: user
              password: redhat
              chpasswd: { expire: False }
          name: cloudinitdisk