apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: create-mysqldump-from-database-vm-
  namespace: pipelines-demo
spec:
  pipelineRef:
    name: create-mysqldump-from-database-vm
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
