apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: deny-by-default
  namespace: vm2
  annotations:
    k8s.v1.cni.cncf.io/policy-for: vm2/vm2-nad
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 200.0.0.1/32