apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm1-nad
  namespace: vm1
spec:
  config: |
    {
            "cniVersion": "0.4.0", 
            "name": "my-layer2-network", 
            "type": "ovn-k8s-cni-overlay", 
            "topology": "layer2", 
            "netAttachDefName": "vm1/vm1-nad" 
    }